# Generated by Django 4.0.5 on 2022-06-27 12:50

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('powers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('small_uuid', django_extensions.db.fields.ShortUUIDField(blank=True, editable=False)),
                ('fighter1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_contender', to='fights.fighter')),
                ('fighter2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_contender', to='fights.fighter')),
            ],
        ),
    ]
